// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA205G0PA0nd3rJ-RthRB57P4EpVeDxgBo',
    appId: '1:278179211836:web:b5aae9b66ac3ba6a603139',
    messagingSenderId: '278179211836',
    projectId: 'web-valuta',
    authDomain: 'web-valuta.firebaseapp.com',
    storageBucket: 'web-valuta.firebasestorage.app',
    measurementId: 'G-Q9724TV4GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_M0yYlms4SqVm_0pBpZsqRNJzjQug818',
    appId: '1:278179211836:android:a74d87067b16c96a603139',
    messagingSenderId: '278179211836',
    projectId: 'web-valuta',
    storageBucket: 'web-valuta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVNu8vmTjFHxfkMGMRdA1rWqaYFXJpgw',
    appId: '1:278179211836:ios:7a39472eabc32761603139',
    messagingSenderId: '278179211836',
    projectId: 'web-valuta',
    storageBucket: 'web-valuta.firebasestorage.app',
    iosBundleId: 'com.example.webValuta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVNu8vmTjFHxfkMGMRdA1rWqaYFXJpgw',
    appId: '1:278179211836:ios:7a39472eabc32761603139',
    messagingSenderId: '278179211836',
    projectId: 'web-valuta',
    storageBucket: 'web-valuta.firebasestorage.app',
    iosBundleId: 'com.example.webValuta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA205G0PA0nd3rJ-RthRB57P4EpVeDxgBo',
    appId: '1:278179211836:web:c05bef0c0898f122603139',
    messagingSenderId: '278179211836',
    projectId: 'web-valuta',
    authDomain: 'web-valuta.firebaseapp.com',
    storageBucket: 'web-valuta.firebasestorage.app',
    measurementId: 'G-XZLPSX9TBJ',
  );
}
